#!/bin/dash

# before we can copy files into the index, we first need to check if the repo exists
if [ ! -d ".legit" ]
then  
    # if it doesn't exist, we cannot add files so we print an error message and exit
    echo "legit-add: error: no .legit directory containing legit repository exists" >&2
    exit 1
fi

# we then test to ensure the correct arguments are given
if [ $# -eq 0 ]
then
    # if the correct arguments aren't given, we print the correct usage and exit
    echo "usage: legit-add <filenames>" >&2
    exit 1
fi

# for all arguments given, we want to ensure none of them start with a dash
for testDashFile in "$@"
do
    # we simply take the filename and use egrep to make sure it starts with a dash
    testDash=`echo $testDashFile | egrep '^-'`
    if [ $testDash ] 
    then
        # if a file starting with a dash did exist, then we print an error and exit
        echo "usage: legit-add <filenames>" >&2
        exit 1
    fi
done


# we also want to check that all the supplied command line arguments are valid files
for testFile in "$@"
do
    # we first want to check the filenames are valid
    testValidFilename=`echo $testFile | egrep '^[a-zA-Z0-9][a-zA-Z0-9.-_]*$'`
    if [ ! $testValidFilename ]
    then
        # if the filename wasn't valid, we print an error message and exit
        echo "legit-add: error: invalid filename '$testFile'" >&2
        exit 1
    fi
    
    # if the filename was valid, we also want to check that it exists
    if [ ! -e "$testFile" ]
    then
        # if the file doesn't exist in the directory, we also check if it exists
        # in the index.
        if [ ! -e ".legit/index/$testFile" ]
        then
            # if a file doesn't exist, we give an error message and exit
            echo "legit-add: error: can not open '$testFile'" >&2
            exit 1
        fi
    fi
done

# once we know that we can add all the supplied files, we create an index subdirectory 
# in .legit (if it doesn't already exist)
index=".legit/index"
if [ ! -d "$index" ]
then
    mkdir "$index"
fi

# for all the files given as arguments, we copy their contents into this index
for file in "$@"
do
    # if the file exists in the directory, then we copy it across to the index
    if [ -e "$file" ]
    then
        cp "$file" "$index/$file"
    # if the file doesn't exist in the directory, then we want to remove it from the index
    else
        rm "$index/$file"
    fi
done

exit 0


